"""On-disk image storage and the ``/images/<name>`` reference used across transports.

Images (uploaded by the user or generated by a tool) live as files under ``config.images_path`` and are
referred to everywhere else by a lightweight ``/images/<name>`` reference: it is what the web server
serves (see ``frontends/web.py``), what a persisted session stores in place of inline base64 (see the
compaction helpers in ``assistant.py``), and what a generated-image tool returns.

The split matters for two reasons. Sessions stay small: ``sessions.json`` holds a short reference, not a
multi-KB data URL per image. And the model still gets pixels: a reference is re-read from disk and
base64-inlined only at the moment a turn is sent, because the model request must carry base64 (the web
server binds to localhost, so a provider cannot fetch a ``/images/`` URL itself).

Filenames are content-addressed (sha256 of the bytes), so the same image uploaded twice is stored once
and a reference is stable across restarts.
"""

from __future__ import annotations

import base64
import hashlib
import mimetypes
import re
from pathlib import Path
from typing import Optional

# The public URL prefix the web server serves images at, and the marker that identifies a compacted
# reference inside stored message content. Kept together so both sides agree on one spelling.
ROUTE_PREFIX = "/images/"

_DATA_URL_RE = re.compile(r"^data:(?P<mime>image/[^;]+);base64,(?P<data>.+)$", re.DOTALL)


def is_reference(url: str) -> bool:
    """True if *url* is one of our ``/images/<name>`` references (as opposed to a data URL or http URL)."""
    return isinstance(url, str) and url.startswith(ROUTE_PREFIX)


def _extension_for(mime: str) -> str:
    return mimetypes.guess_extension(mime) or ".png"


def save_data_url(images_path: Path, data_url: str) -> Optional[str]:
    """Write a base64 image data URL to ``images_path`` and return its ``/images/<name>`` reference.

    Returns ``None`` if *data_url* is not a base64 image data URL. The filename is the sha256 of the
    decoded bytes, so re-saving identical bytes is idempotent.
    """
    match = _DATA_URL_RE.match(data_url)
    if match is None:
        return None
    raw = base64.b64decode(match.group("data"))
    name = hashlib.sha256(raw).hexdigest() + _extension_for(match.group("mime"))
    images_path.mkdir(parents=True, exist_ok=True)
    path = images_path / name
    if not path.exists():
        path.write_bytes(raw)
    return ROUTE_PREFIX + name


def save_file(images_path: Path, source: Path) -> str:
    """Copy a local image file into ``images_path`` (content-addressed) and return its reference."""
    raw = source.read_bytes()
    mime, _ = mimetypes.guess_type(source.name)
    suffix = source.suffix or (_extension_for(mime) if mime else ".png")
    name = hashlib.sha256(raw).hexdigest() + suffix
    images_path.mkdir(parents=True, exist_ok=True)
    path = images_path / name
    if not path.exists():
        path.write_bytes(raw)
    return ROUTE_PREFIX + name


def reference_to_path(images_path: Path, reference: str) -> Optional[Path]:
    """Resolve a ``/images/<name>`` reference to a file under ``images_path``, or ``None`` if invalid.

    Rejects anything that would escape ``images_path`` (the reference must be a bare basename)."""
    if not is_reference(reference):
        return None
    name = reference[len(ROUTE_PREFIX) :]
    if name != Path(name).name or not name:
        return None
    path = images_path / name
    return path if path.is_file() else None


def reference_to_data_url(images_path: Path, reference: str) -> Optional[str]:
    """Read the file behind a ``/images/<name>`` reference and return a base64 data URL, or ``None``."""
    path = reference_to_path(images_path, reference)
    if path is None:
        return None
    mime, _ = mimetypes.guess_type(path.name)
    if mime is None or not mime.startswith("image/"):
        mime = "image/png"
    b64 = base64.b64encode(path.read_bytes()).decode("ascii")
    return f"data:{mime};base64,{b64}"
